// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR19ymgkBTF2gJpJTgzZ02qieml3ymckY',
    appId: '1:1078496083683:web:520417ab6d20a8e9640fd6',
    messagingSenderId: '1078496083683',
    projectId: 'techprohelpline',
    authDomain: 'techprohelpline.firebaseapp.com',
    databaseURL: 'https://techprohelpline-default-rtdb.firebaseio.com',
    storageBucket: 'techprohelpline.appspot.com',
    measurementId: 'G-RK9SERFX0F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtxK7Iv9NLpba_ShVgWKtpfZDLBhmTToY',
    appId: '1:1078496083683:android:a0c13edd11f8aa00640fd6',
    messagingSenderId: '1078496083683',
    projectId: 'techprohelpline',
    databaseURL: 'https://techprohelpline-default-rtdb.firebaseio.com',
    storageBucket: 'techprohelpline.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyzJn3MdSRpxEfA7vYSxttIDAtkLnQh6Y',
    appId: '1:1078496083683:ios:4bd4f1ea8a5ad2c1640fd6',
    messagingSenderId: '1078496083683',
    projectId: 'techprohelpline',
    databaseURL: 'https://techprohelpline-default-rtdb.firebaseio.com',
    storageBucket: 'techprohelpline.appspot.com',
    iosClientId: '1078496083683-eft54i6eg7jpf6bss973mnkhpv05et27.apps.googleusercontent.com',
    iosBundleId: 'com.example.techprohelpline',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyzJn3MdSRpxEfA7vYSxttIDAtkLnQh6Y',
    appId: '1:1078496083683:ios:7cccd9b7b3e1fd7f640fd6',
    messagingSenderId: '1078496083683',
    projectId: 'techprohelpline',
    databaseURL: 'https://techprohelpline-default-rtdb.firebaseio.com',
    storageBucket: 'techprohelpline.appspot.com',
    iosClientId: '1078496083683-hfh5oc7u6nvpbpq6na1fpijl295d5u7b.apps.googleusercontent.com',
    iosBundleId: 'com.example.techprohelpline.RunnerTests',
  );
}
